### ISSUE TITLE
New design

### ISSUE THREAD

**Issue by dominikwilkowski** [dominikwilkowski/bronzies#2]
Needs a design as there is none right now. Wireframes have been made by Dylan but still waiting for a proper design.

**Comment by dominikwilkowski** [comment]
first preview:

![screen shot 2015-02-13 at 1 35 29 pm](https://cloud.githubusercontent.com/assets/1266923/6181321/39361fa2-b385-11e4-94c2-bcd684834118.png)

**Comment by Fellmeister** [comment]
Oh.My.god.
That is some sweet, sweet design work there! My mum's off on Sunday so I should have some time to play with this stuff again.

Seriously, that is beautiful!

Date: Thu, 12 Feb 2015 18:36:30 -0800

**Comment by dominikwilkowski** [comment]
yeah! I hosted the app now here:

http://bronzies.com/bronze/new/signals.html

All functionality is done... just waiting on design to finish.
Got loads in now. All completely refactored and running off of the REST server...
iOS and Droid apps to follow... will need you to test the droid ones soon
